version: 2
updates:
- package-ecosystem: bundler
  directory: "/omnibus"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/src/supermarket/engines/fieri"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/src/supermarket"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
