# This is a basic workflow to help you get started with Actions

name: Simplecov Report

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
uses: aki77/simplecov-report-action@v1.3.1

with:
  token: null
