name: Simplecov Report

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  simplecov-scan:
    name: Simplecov Report
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: rspec spec
      # Checkout the repository to the GitHub Actions runner
      - name: Simplecov
        uses: aki77/simplecov-report-action@v1.3.1
