development:
  adapter: postgresql
  database: supermarket_development
  host: <%= ENV['POSTGRES_IP'] || 'localhost' %>
  pool: 30
  username: supermarket
  password: password

test:
  adapter: postgresql
  database: supermarket_test
  host: <%= ENV['POSTGRES_IP'] || 'localhost' %>
  username: supermarket_user
  password: password

production:
  username: supermarket
  password: password
  host: localhost
  adapter: postgresql
  database: supermarket_development
